dhd: Fix Android 6 <= based builds
this problem happens if Android version is <= 6 and there is file
hybris_extras.rc in system/etc/init. It is introduced by commit
1fb8758dafa5 ("dhd: add support for one extra init rc, which can be
used to provide info from the adaptation to sfos")

In this case build_packages.sh fails with following error:

$ rpm/dhd/helpers/build_packages.sh

+ '[' 4 -ge 7 ']'
+ echo ''
+ '[' -f ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc ']'
+ cp -a ./out/target/product/hammerhead/system/etc/init/hybris_extras.rc /media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/
cp: cannot create regular file `/media/data/port/android/installroot/usr/libexec/droid-hybris/system/etc/init/': No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.SrHvD1 (%install)